version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use the CircleCI Node.js Docker image
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Install Dependencies
          command: npm install  # Install Node.js dependencies

workflows:
  version: 2
  build_and_test:
    jobs:
      - build  # Run the build job
