version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t node-microservice .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push node-microservice

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
