# node-microservice-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: node-microservice
spec:
  type: NodePort
  selector:
    app: node-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
